#!/bin/bash

#./apkinstall                            && \
cp ./app/build/outputs/bundle/release/app-release.aab .      && \
./versionreport                         && \
git commit -m 'build/s' -a              && \
git push
