#!/bin/bash
sha512sum app-release.aab > release-checksum
sha512sum app-debug.apk > dev-checksum

VERSION_CODE=`git log -p | egrep 'release-checksum|dev-checksum' | wc -l`
echo "VERSION_CODE=${VERSION_CODE}" > version.properties 

dt=$(date '+%Y%m%d_%H%M%S');
VERSION_NAME=${dt}'.'`git branch --show-current`'.'`git rev-parse --short HEAD`
echo "VERSION_NAME=${VERSION_NAME}" >> version.properties 

cat version.properties
